### PR TITLE
Create a web component similar to the Map Viewer app

### PR DESCRIPTION
**Pull request by jahow**
image

No special functionality for now. Planned functionalities are:
* possibility to specify one or several uuid to load layers from these records at startup
* allow adding layers from search results which are shown in another web component

Part of #337

### CODE REVIEW

**Review by fgravin — COMMENTED** [review]
Easy !
Seems not working though :smiley: 
https://geonetwork.github.io/geonetwork-ui/map-viewer-add-wc/demo/webcomponents/gn-map-viewer.sample.html

Nothing happens on layer adding.

**Comment by jahow** [comment]
Yep that's because it needs #358... when doing the pagination PR I introduced the `(buttonClick)` event on the gn-ui-button instead of the native `(click)`, and so it broke the map-viewer "add-layer" buttons.

**Comment by fgravin** [comment]
> I introduced the `(buttonClick)` event on the gn-ui-button instead of the native `(click)`

On the way to `buttonClickAndSpin` then :wink:

**Comment by fgravin** [comment]
Ok so if you checked that the WC is working on main you can merge, thanks

**Comment by jahow** [comment]
confirmed :sunglasses:

**Pull request merged**
