### PR TITLE
Fix translation for isOpenData

### PR DESCRIPTION
**Pull request by tkohr**
Use translate pipe for string displayed in badge's ng-content.

### CODE REVIEW

**Comment by jahow** [comment]
Weird, why is the `translate` directive not working there?

**Comment by tkohr** [comment]
> Weird, why is the `translate` directive not working there?

Good question, I just stumbled on other cases where people had this problem when translating things passed into `ng-content`.

**Comment by fgravin** [comment]
> Good question, I just stumbled on other cases where people had this problem when translating things passed into `ng-content`

maybe because you put it on the component tag ? if you add a div in there what happens ?

**Comment by tkohr** [comment]
> > Good question, I just stumbled on other cases where people had this problem when translating things passed into `ng-content`
> 
> maybe because you put it on the component tag ? if you add a div in there what happens ?

You're right @fgravin, thanks, I adapted accordingly

**Comment by tkohr** [comment]
> In general, using a `<span>` for inline text is better; semantically `<p>` means paragraph :) thanks!

Yep, thanks, I adapted accordingly.

**Pull request merged**
