### PR TITLE
Datahub - Map is not reset when navigating between datasets

### PR DESCRIPTION
**Pull request by rcaplier**
### Description

This PR makes the map reset when exiting the dataset.

### Quality Assurance Checklist

- [ ] Commit history is devoid of any _merge commits_ and readable to facilitate reviews
- [x] If **new logic** ⚙️ is introduced: unit tests were added
- [ ] If **new user stories** 🤏 are introduced: E2E tests were added
- [ ] If **new UI components** 🕹️ are introduced: corresponding stories in Storybook were created
- [ ] If **breaking changes** 🪚 are introduced: add the `breaking change` label
- [ ] If **bugs** 🐞 are fixed: add the `backport <release branch>` label
- [ ] The [documentation website](docs) 📚 has received the love it deserves

---

**This work is sponsored by MEL**.

### CODE REVIEW

**Review by jahow — CHANGES_REQUESTED** [review]
I'm not sure this is the right way to approach this issue. I would say that instead we should try to reinitialize the map when a new dataset is opened, instead of assuming that the map will be empty initially (which is what we currently do).

**Comment by cmoinier** [comment]
> I'm not sure this is the right way to approach this issue. I would say that instead we should try to reinitialize the map when a new dataset is opened, instead of assuming that the map will be empty initially (which is what we currently do).

I looked into this because my PR is kind of related. I think `dropdownChoices$` take some time to change/reload the new links when you switch records, creating this issue. I think that emptying this Observable when the user leaves the page should do the trick.

**Comment by jahow** [comment]
> I looked into this because my PR is kind of related. I think `dropdownChoices$` or `compatibleMapLinks$` perhaps take some time to change/reload the new links when you switch records, creating this issue. I think that emptying this Observable when the user leaves the page should do the trick.

I agree that we should work with observables. Why not do a `startwith` somewhere to make sure that as soon as a record is opened an empty map is shown? Instead of clearing it on record close, which would solve the issue in a more indirect way.

**Comment by rcaplier** [comment]
> > I looked into this because my PR is kind of related. I think `dropdownChoices$` or `compatibleMapLinks$` perhaps take some time to change/reload the new links when you switch records, creating this issue. I think that emptying this Observable when the user leaves the page should do the trick.
> 
> I agree that we should work with observables. Why not do a `startwith` somewhere to make sure that as soon as a record is opened an empty map is shown? Instead of clearing it on record close, which would solve the issue in a more indirect way.

I tried the startWith solution and it didn't work for me... And then I discovered that we actually have something to create an emptyMap in the mapUtilsManager.

**Review by jahow — APPROVED** [review]

**Pull request merged**
