### PR TITLE
[Datahub] [Redesign] Licence and usages panel

### PR DESCRIPTION
**Pull request by cmoinier**
### Description

This PR introduces changes for the redesign of the licence and usages panel. It includes the following changes : 

- [x] Rename the existing panel and move it to the first place
- [x] change the style of the usage conditions
- [x] show usage limitations separately
- [ ] improve the mapper to better split the licenses, restrictions and conditions (it gets mixed up sometimes)

### Screenshots

image

### Quality Assurance Checklist

- [x] Commit history is devoid of any _merge commits_ and readable to facilitate reviews
- [x] If **new user stories** 🤏 are introduced: E2E tests were added
- [ ] The [documentation website](docs) 📚 has received the love it deserves

**This work is sponsored by [GeoCat](https://www.geocat.admin.ch/fr/home/evenements.html)**.

### CODE REVIEW

**Comment by fgravin** [comment]
oups sorry i clicked on the "ready for review" button by accident :upside_down_face:

**Comment by ronitjadhav** [comment]
Refined the layout for the License and Condition panels, now distinctly sectioned as follows:

- **Licenses**: Displayed first, where each license with a URL is clickable for direct access.
- **Legal Constraints**: Positioned after licenses, presented without a specific title to maintain a seamless flow.
- **Other Constraints**: Listed under "Additional conditions," enhancing the structured presentation of information.

Implemented gnUiLinkify for all licenses, legal and other constraints, enabling URLs to be opened in new tabs, improving accessibility and user interaction.

**Screenshot:**

image

**Comment by fgravin** [comment]
Thanks @ronitjadhav, is it ready for a review ?

**Comment by jahow** [comment]
@fgravin the changes in the metadata model affects the metadata-converter app which needs to be adjusted, but (correct if me if I'm wrong @ronitjadhav) this is ready for review, yes; note that this was in part done in pair-programming with me

**Comment by jahow** [comment]
@ronitjadhav I've added a few commits to get closer to the mockup & improve the HTML template. The md-converter app is now also working.

@fgravin feel free to make a review! thanks

**Review by jahow — APPROVED** [review]

**Comment by jahow** [comment]
I have adjusted the constraints to use `gn-ui-markdown-parser`, so that the constraints can actually contain rich text (line breaks, lists etc.). This is now finished IMO, I will merge when green.

**Pull request merged**
