### PR TITLE
NPM package: Add more exports and fix dependencies

### PR DESCRIPTION
**Pull request by tkohr**
### Description

This PR adds some more exports to the npm package.

https://github.com/geonetwork/geonetwork-ui/commit/04df6031516966d01d476767353589e0ec8cf1e1 also tends to resolve the following error encountered using the latest ([2.2.0-dev.46643468](https://www.npmjs.com/package/geonetwork-ui/v/2.2.0-dev.46643468)) release:

```
✘ [ERROR] Could not resolve "marked"

    node_modules/geonetwork-ui/fesm2022/geonetwork-ui.mjs:61:23:
      61 │ import { marked } from 'marked';
         ╵                        ~~~~~~~~

  You can mark the path "marked" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "basiclightbox"

    node_modules/geonetwork-ui/fesm2022/geonetwork-ui.mjs:76:31:
      76 │ import * as basicLightbox from 'basiclightbox';
```

Note: Somehow, I cannot even include the `<gn-ui-markdown-parser>` component in an external project, even though it is exported. Not sure if this is related to the dependency issue above.

### Quality Assurance Checklist

- [ ] Commit history is devoid of any _merge commits_ and readable to facilitate reviews
- [ ] If **new logic** ⚙️ is introduced: unit tests were added
- [ ] If **new user stories** 🤏 are introduced: E2E tests were added
- [ ] If **new UI components** 🕹️ are introduced: corresponding stories in Storybook were created
- [ ] If **breaking changes** 🪚 are introduced: add the `breaking change` label
- [ ] If **bugs** 🐞 are fixed: add the `backport <release branch>` label
- [ ] The [documentation website](docs) 📚 has received the love it deserves

### CODE REVIEW

**Review by jahow — COMMENTED** [review]
I think the new dependencies should be added there as well: https://github.com/geonetwork/geonetwork-ui/blob/04df6031516966d01d476767353589e0ec8cf1e1/package/package.json#L39

with this PR you're just suppressing the warnings, but the dependencies are still not included in the package.

I know, this workflow is tedious! I hope we can find some time to automate that in the future.

**Comment by tkohr** [comment]
> I think the new dependencies should be added there as well:
> 
> https://github.com/geonetwork/geonetwork-ui/blob/04df6031516966d01d476767353589e0ec8cf1e1/package/package.json#L39
> 
Right, thanks, I've added them there as well.

**Review by fgravin — APPROVED** [review]

**Comment by tkohr** [comment]
Hum, using the `<gn-ui-markdown-parser>` works well now, but I'm still getting `Internal server error: Missing "./libs/common/domain/src/lib/platform.service.interface" specifier in "geonetwork-ui" package` when trying to use `PlatformServiceInterface`. I don't see the index.ts that I've added in this PR in the generated package. Any idea where this export is failing @jahow ?

There's also already a new dep (`@geospatial-sdk/geocoding`) missing in the package, that I'll add in a follow-up PR. Yes I guess we'll have to try to automate this in the long run.

**Comment by tkohr** [comment]
To fix the dependency, I've opened https://github.com/geonetwork/geonetwork-ui/pull/793

Regarding the missing `PlatformServiceInterface` export, we might not need it (yet), but I'm still curious.

**Pull request merged**
