### PR TITLE
Automatically publish NPM package on every commit on main branch

### PR DESCRIPTION
**Pull request by jahow**
This should also publish the package on every release, as well as attempt a build of the npm package on every PR to make sure that it doesn't break.

### CODE REVIEW

**Review by fgravin — APPROVED** [review]
LGTM
I would test the artifact actions via a PR comment though, to be sure that it works as expected.

**Review by fgravin — COMMENTED** [review]
Do you erase the commit i've pushed yesterday about the universal thing ?

**Comment by jahow** [comment]
> Do you erase the commit i've pushed yesterday about the universal thing ?

oh yes sorry I forced push without pulling first, I'll readd it

**Comment by jahow** [comment]
Readded here: https://github.com/geonetwork/geonetwork-ui/pull/760
with also updated dependencies

**Pull request merged**
