### PR TITLE
[datahub] extended filtering options and improved organisation and license filters

### PR DESCRIPTION
**Pull request by alexarobu**
This could be an alternative to the filters already in there and would look like this:
image

I think an even better option would be enabling the user to pick from a given list of filters (as part of the `default.toml` config options). I think standards and INSPIRE keywords are quite important and quite commonly used in GeoNetwork as search filters too (from what I could see in our users' use cases).

### CODE REVIEW

**Comment by jahow** [comment]
Thanks for the suggestion, this is something that has been requested several times and is currently planned in the upcoming developments at Camptocamp.

Current filterable fields are exposed by the FieldsService class here: https://github.com/geonetwork/geonetwork-ui/blob/main/libs/feature/search/src/lib/utils/service/fields.service.ts

These could easily be made configurable from the `default.toml` file by simply specifying them by field name.

**Review by jahow — COMMENTED** [review]
I think this change looks quite reasonable! First thing would probably be to set up your IDE to run prettier automatically on every save, otherwise you have to run the `npx nx run format:write` task manually.

Please feel free to refer to https://github.com/geonetwork/geonetwork-ui/blob/main/CONTRIBUTING.md#contributing-code for more info, and don't hesitate to contribute to the docs if it isn't as helpful as you would expect, thanks!

**Comment by alexarobu** [comment]
> I think this change looks quite reasonable! First thing would probably be to set up your IDE to run prettier automatically on every save, otherwise you have to run the `npx nx run format:write` task manually.
> 
> Please feel free to refer to https://github.com/geonetwork/geonetwork-ui/blob/main/CONTRIBUTING.md#contributing-code for more info, and don't hesitate to contribute to the docs if it isn't as helpful as you would expect, thanks!

@jahow thanks for the reminder, I ran formatting and linting on all code (some other files changed too- see my latest commit)

**Comment by fgravin** [comment]
Seems there is still some format issue, could you run `npm run format` instead please ?
Also, you should amend your commit instead of adding a new one, the clearer the git history the better :smiley: 
One commit should be enough for your PR.

Thanks in advance.
The CI should run and warn you about the formatting, but it's not running from your fork, i'll try to figure that out.
Cheers

**Comment by alexarobu** [comment]
@fgravin gotcha! I removed the other commit and added any changes `npm run format` made into the same commit

**Comment by fgravin** [comment]
Hi @alexarobu 

Ok for the format, it's a bit weird that there are changes which was not breaking before but ok :smile: 
Note that you have a failing test https://github.com/geonetwork/geonetwork-ui/actions/runs/4941200866/jobs/8833591106?pr=471

The `Snyk Security` fail meight be because it comes from a fork, don't bother about this one (we will figure that out) but fix the `Checks` one please, thanks

**Comment by fgravin** [comment]
@alexarobu you should not `merge` `main` into a PR branch, the workflow is to `rebase`.
Sorry to be picky, it will be easier for you to contribute for you next PRs but for the first one it's better to follow all the good practices :smile: 

So, the history should be clean and relevant.
Here you should have only one commit.
So, locally, you really need to learn the `rebase`, `rebase -i`, `--amend` and all git history management thing.
For instance, if you want to align your branch on main you do a
```
git fetch upstream
git rebase upstream/main
git push -f origin/my_branch
```
I aslo would recommend you to create a dedicated branch for your PR instead of using your `main`.

Thanks a lot and sorry for all the back and fourth

**Comment by alexarobu** [comment]
@fgravin Hey! :sweat_smile: I'll have a look and action your suggestions tomorrow. Apologies I didn't reply all day, I was on a training course. 

Thanks for all the advice and patience and sorry for the headaches :see_no_evil:. Don't worry about being picky, it's good for me to learn all this stuff and I don't want to break anything with my changes :grimacing:

**Pull request closed without merging**
