### PR TITLE
Button type directly in class

### PR DESCRIPTION
**Pull request by f-necas**
Fix buttons not using their tailwind classes.

### CODE REVIEW

**Review by fgravin — COMMENTED** [review]
I don't really see the meaning of this change, it complexifies the button api.
Couldn't you adopt another approach ?

**Comment by f-necas** [comment]
@fgravin It's not really a big change, instead of `primary` we would have to write `btn-primary`. 

It's just a small step to fix the display of not secondary buttons.

It's intended to get rid of this gn-ui-button either which will result in a `<button type="button" class="btn-primary>" `

**Review by jahow — COMMENTED** [review]
Wait, how come this fixes the issue? edit: sorry, just saw the above messages. I think if we're going to modify every gn-ui-button usage then we might as well use the opportunity to get rid of this component altogether? But I would be very interested to know the underlying reason for this problem.

**Review by jahow — APPROVED** [review]
Thanks!

**Pull request merged**
