### PR TITLE
Datahub: Fix cutoff expanded abstract

### PR DESCRIPTION
**Pull request by tkohr**
### Description

This PR replaces a margin with a padding in the max-lines ng-content to prevent cutoffs on expanded abstracts that may occur with markup since margins are not taken into account when calculating the expanded max height via `getBoundingClientRect`.

The bug was detected on https://github.com/camptocamp/mel-dataplatform/pull/102

### Screenshots

image

### Quality Assurance Checklist

- [ ] Commit history is devoid of any _merge commits_ and readable to facilitate reviews
- [ ] If **new logic** ⚙️ is introduced: unit tests were added
- [ ] If **new user stories** 🤏 are introduced: E2E tests were added
- [ ] If **new UI components** 🕹️ are introduced: corresponding stories in Storybook were created
- [ ] If **breaking changes** 🪚 are introduced: add the `breaking change` label
- [ ] If **bugs** 🐞 are fixed: add the `backport <release branch>` label
- [ ] The [documentation website](docs) 📚 has received the love it deserves

---

**This work is sponsored by [MEL](https://data.lillemetropole.fr/)**.

### CODE REVIEW

**Review by jahow — COMMENTED** [review]
I'm not sure this is the right approach: adding padding to the block will make the "read more" button appear without a need for it.

On main:
image

On this PR:
image

**Comment by tkohr** [comment]
Oh thanks, I completely missed that. I'll have a look how to handle this.

**Comment by jahow** [comment]
Is it possible that the size computation is incorrect because of fonts loading or something like that?

**Comment by tkohr** [comment]
So as it turned out it was the `margin-top` from the first markdown heading that caused the issue calculating the height via `getBoundingClientRect`. Thanks @jahow !

**Review by jahow — APPROVED** [review]

**Pull request merged**
