### PR TITLE
Set favicon default url to /favicon.ico and allow to customize it

### PR DESCRIPTION
**Pull request by f-necas**
The default favicon points to `/assets/favicon.ico`. As favicon is often provided in root, it's useful to have it there.

### CODE REVIEW

**Review by fgravin — COMMENTED** [review]
Could you give more context ?
Who can't put the favicon in the assets ?
Note that it will break all actual configs.

**Comment by jahow** [comment]
This is unfortunately susceptible to break all existing favicons. I would rather look for a way to customize the favicon path, for instance on the docker image startup why rewriting parts of the HTML, like we do for adding preload links here:
https://github.com/geonetwork/geonetwork-ui/blob/f46b998c18fc5db63319f25a497ae05b708ac49f/tools/docker/docker-entrypoint.sh#L38-L55

Outside of a docker usage, I feel like having a favicon point to the correct place should be easier.

**Comment by f-necas** [comment]
@jahow Is it ok, if we remove it like this ?

**Comment by jahow** [comment]
I'm sorry for all the back and forth on this issue, but I think we shouldn't merge it like that.

The way I see it currently, we should:
1. remove the favicon like in this PR
2. add an option in the config file to point to a place for a custom favicon if none is available at `/favicon.ico`; this is e.g. the case for www.geocat.ch, which gives a 404 for https://www.geocat.ch/favicon.ico

Otherwise we're losing functionality

**Comment by f-necas** [comment]
@jahow I've added the possibility to implement it from toml file.

**Review by jahow — COMMENTED** [review]
This looks better now, thanks! I've left some comments, please wait for 2.1 to be out before merging this.

I added a "breaking change" label so that we can remember that this new setting will be mandatory for people that don't have a favicon at their website's root. Please also update the PR title accordingly, so that it makes sense when it shows up in the changelog :slightly_smiling_face:  thanks!

**Review by jahow — APPROVED** [review]
All good thanks!

**Pull request merged**
